//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregaPedido
    {
        public int id_Entrega { get; set; }
        public Nullable<int> F_Pedido { get; set; }
        public Nullable<int> F_Repartidor { get; set; }
        public System.DateTime Salida { get; set; }
        public Nullable<System.DateTime> SeEntrego { get; set; }
        public string Estado { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Repartidor Repartidor { get; set; }
    }
}
