//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id_prod { get; set; }
        public string NombreProd { get; set; }
        public int Peso { get; set; }
        public short Cantidad { get; set; }
        public double PrecioFinal { get; set; }
        public string NotaEspecial { get; set; }
        public Nullable<int> F_Pedido { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
