//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int id_ubicacion { get; set; }
        public string Colonia { get; set; }
        public string Calleynumero { get; set; }
        public string Municipio { get; set; }
        public string Ciudad { get; set; }
        public string Referencia { get; set; }
        public string Caracteristica { get; set; }
        public string CP { get; set; }
        public Nullable<int> F_Cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
